<?php
include("../../../path.php");
include('../../controllers/invoicesController.php');

$currentPage = 'invoices';
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>e-MSI remote task</title>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" integrity="sha384-KA6wR/X5RY4zFAHpv/CnoG2UW1uogYfdnP67Uv7eULvTveboZJg0qUpmJZb5VqzN" crossorigin="anonymous">
  <!-- Reset CSS -->
  <link rel="stylesheet" href="../../../assets/css/reset.css">
  <!-- Main styles -->
  <link rel="stylesheet" href="../../../assets/css/main.css">

</head>

<body id="body" class="preload">

  <!-- Page wrapper -->
  <div class="page-wrapper">

    <!-- Left section (sidebar) -->
    <?php include(ROOT_PATH . '/app/includes/sidebar.inc.php'); ?>

    <!-- Right section (content) -->
    <div id="right" class="content">

      <!-- Top nav/header -->
      <?php include(ROOT_PATH . '/app/includes/header.inc.php'); ?>

      <h1>Faktury VAT</h1>

      <!-- First table generated by JS (NOT IN USE) -->
      <!-- <div class="content-row">
        <table id="table">
          <thead id="thead">
            <tr>
              <th>Lp.</th>
              <th>Opis</th>
              <th>MPK</th>
              <th>Netto</th>
              <th>Ilość</th>
              <th>VAT</th>
              <th>Brutto</th>
              <th>Wartość netto</th>
              <th>Wartość brutto</th>
            </tr>
          </thead>
        </table>
      </div>
      <br><br><br><br> -->

      <!-- Second table -->
      <div class="content-row">

        <div class="action-btn-wrapper">
          <button id="selectNumbersBtn" class="action-btn">Kwoty powyżej 1000 PLN Netto</button>
        </div>

        <table>
          <thead>
            <tr>
              <th>Lp.</th>
              <th>Opis</th>
              <th>MPK</th>
              <th>Netto</th>
              <th>Ilość</th>
              <th>VAT</th>
              <th>Brutto</th>
              <th>Wartość netto</th>
              <th>Wartość brutto</th>
            </tr>
          </thead>
          <tbody>
            <?php if (!empty($invoices)) : ?>
              <?php foreach ($invoices as $index => $invoice) : ?>
                <tr class="invoice-row">
                  <form action="invoices.php" method="POST">

                    <!-- ID -->
                    <input type="hidden" name="id" value="<?= $invoice['id']; ?>">

                    <!-- Lp. -->
                    <td><?= $index + 1 . '.'; ?></td>

                    <!-- Opis -->
                    <td>
                      <input type="hidden" name="description" value="<?= $invoice['description']; ?>">
                      <?= $invoice['description']; ?>
                    </td>

                    <!-- MPK -->
                    <td>
                      <input type="hidden" name="mpk" value="<?= $invoice['mpk']; ?>">
                      <?= $invoice['mpk']; ?>
                    </td>

                    <!-- Kwota netto -->
                    <td class="net-prices">
                      <input class="net-prices-value" type="text" name="net" value="<?= number_format($invoice['net'], 2, ',', ''); ?>">
                    </td>

                    <!-- Ilość -->
                    <td class="quantities">
                      <input type="text" name="quantity" value="<?= $invoice['quantity']; ?>">
                    </td>

                    <!-- VAT -->
                    <td class="vat-rates">
                      <select name="vat_id">
                        <?php foreach ($vat_rates as $index => $vat_rate) : ?>
                          <?php if ($vat_rate['id'] == $invoice['vat_id']) : ?>
                            <option value="<?= $index + 1; ?>" selected><?= $vat_rate['rate']; ?></option>
                          <?php else : ?>
                            <option value="<?= $index + 1; ?>"><?= $vat_rate['rate']; ?></option>
                          <?php endif; ?>
                        <?php endforeach; ?>
                      </select>
                    </td>

                    <!-- Kwota brutto -->
                    <td>
                      <?php foreach ($vat_rates as $vat_rate) : ?>
                        <?php if ($vat_rate['id'] == $invoice['vat_id'] and $vat_rate['rate'] != 'ZW' and $vat_rate['rate'] != 'NP.') : ?>
                          <?= number_format(($invoice['net'] * ((float) $vat_rate['rate'] / 100.00) + $invoice['net']), 2, ',', ''); ?>
                        <?php endif; ?>
                      <?php endforeach; ?>
                    </td>

                    <!-- Wartość netto -->
                    <td>
                      <?= number_format($invoice['net'] * $invoice['quantity'], 2, ',', ''); ?>
                    </td>

                    <!-- Wartość brutto -->
                    <td>
                      <?php foreach ($vat_rates as $vat_rate) : ?>
                        <?php if ($vat_rate['id'] == $invoice['vat_id'] and $vat_rate['rate'] != 'ZW' and $vat_rate['rate'] != 'NP.') : ?>
                          <?= number_format((($invoice['net'] * ((float) $vat_rate['rate'] / 100.00) + $invoice['net']) * $invoice['quantity']), 2, ',', ''); ?>
                        <?php endif; ?>
                      <?php endforeach; ?>
                    </td>

                    <!-- Zaktualizuj -->
                    <td class="update-invoice"><button class="update-invoice-btn" type="submit" name="updateInvoice"><i class="fas fa-redo-alt"></i></button>
                    </td>

                  </form>
                </tr>
              <?php endforeach; ?>
            <?php else : ?>
              <p>Brak rekordów w bazie danych</p>
            <?php endif; ?>
          </tbody>
        </table>

      </div>
    </div>
  </div>

  <script>
  </script>

  <!-- JavaScript -->
  <script src="<?= BASE_URL; ?>/assets/js/script.js"></script>

  <!-- Generate invoices table -->
  <!-- <script src=""></script> -->

  <!-- Check sidebar status -->
  <script src="<?= BASE_URL; ?>/assets/js/sidebarStatus.js"></script>

</body>

</html>